remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
repository: "cesail/cesail.github.io"

title: [Cesai Q. Li]
description: [Ph.D. student in Mathematics] 

include:
  - head-custom.html
